name: Build Docker Image
on:
  push:
    branches:
      - master
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{env.DOCKERHUB_USERNAME}}
            DOCKER_TOKEN: ${{ secret.DOCKER_TOKEN }}
          run: |
            docker login -u $username
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f Dockerfile -t emahdij/tmp-interview:latest
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKERHUB_USERNAME}}/tmp-interview:latest